### ISSUE TITLE
common AEP calculation for turbine and plant

### ISSUE THREAD

**Issue by fzahle** [FUSED-Wind/fusedwind#20]
currently the plant flow module has a class for computing AEP, but this also iterates over wind direction. could we break this up so there's a more basic version that is only a function of wind speed? and should this live in the ``turbine`` with the plant extension living in plant_flow?

**Comment by piredtu** [comment]
I reviewed it, and it's fine from my point of view. I still need to use the code from Katherine in `WeibullWindRose`. What about you @fzahle? Can you use it?

**Comment by fzahle** [comment]
I just need the AEP for a single turbine, so I guess I'd use the aep_weibull_assembly and simply set the turbine_number=1, so OK with me as far as I can see.
