### ISSUE TITLE
review tutorial for plant_cost

### ISSUE THREAD

**Issue by dykesk** [FUSED-Wind/fusedwind#34]
review the plant_cost tutorial code and associated documentation (currently on fusedwind.org); it corresponds at present to the WISDEM format - if changes are suggested, please let me know

**Comment by piredtu** [comment]
Hi Katherine,
I think that the examples are fine. You don't actually run any of them, as far as I could see in the fused_cost_example.py. But I guess this was not the purpose. It was more to show how to use the different assemblies and components
