### ISSUE TITLE
Adapt FUSED-Wind to OpenMDAO v0.12

### ISSUE THREAD

**Issue by fzahle** [FUSED-Wind/fusedwind#59]
The primary task is to ensure that all *output* arrays in components are initialised with a fixed size before run() is called.

**Comment by fzahle** [comment]
I've experimented with some of the turbine components, and after setting the correct sizes of component output arrays my simplified turbine examples run through with only a few other minor changes. Although it was nice not to have to worry about array allocation, it doesn't seem like a big deal to change, at least for my assemblies.

My inclination so far is that it's nicer to split the instantiation and sizing in two, e.g.

    cls.add('pf_splines', SplinedBladePlanform())
    cls.pf_splines.nC = 6
    cls.pf_splines.span_ni = 20
    cls. pf_splines.configure_splines()

but making it part of the instantiation would of course prevent users from forgetting to set these sizes.

For our code wrappers it could, however, be nice not to have to worry about allocation internally in the wrapper assembly. A scenario could be an assembly that sets up an external code, consisting of input file generation, model execution and post processing, all of which will always be executed sequentially and never be connected to anything outside that assembly. @JustinSGray, would it be possible to add a flag to the Assembly class that tells the framework not to worry about array sizes of components inside an assembly?

**Comment by JustinSGray** [comment]
Short answer: Maybe, kind of, sort of... :) 

There are actually two classes of variables in OpenMDAO. 

1) Flattenable: anything (float or array) that could be flattened into a 1-D float array. These are basically differentiable inputs and outputs that use the new distributed array data passing. 

2) Non-Flattenable: Anything else that can't be (or shouldn't be) passed via distributed array. These get passed around more closely to the old system. A copy is made and set into the downstream input. These variables don't need to be initialized before run time at all. We automatically segregate things like lists or integer arrays into class 2. But you can manually force any variable into that class via `noflat=True` metadata.

Now for the catch. Anything non-flattenable can not be used for analytic derivatives. Thats fine for the example you gave where you'd doing a bunch of file i/o stuff in an assembly. That whole thing would have to get FD'd anyway. But just so you know the limitation. 

Also, we currently don't support any non-flattenable data connections in MPI. Its on our list of things to implement. But we have some current problems we're trying to solve in the near term that don't need any non-flattenable stuff but have a bunch of other parallel needs.

**Comment by fzahle** [comment]
In the example I gave, the assembly could potentially be able to deliver derivatives. Everything that is exchanged to the outside is allocated and flattenable, but I would just like the framework to treat that assembly as if it were a single component/block so whatever I do in there is my business. 

As to your last sentence, does that mean that if a problem formulation contains *any* non-flattenable connections, the whole setup will not be runnable under MPI or will it just mean that assembly XX with non-flattenable connections inside can only run on a single node?

**Comment by JustinSGray** [comment]
In your example, you would just mark any internal variables with `noflat=True`. Thats about as close as we can get to "just like a component" because you're actually using our connections to move data around. But noflat should get you what you want. 

Right now, any non flattenable connections will stop you from running in MPI. We don't plan for this limitation to lat too long, but I'm not ready to give you a real target date yet either. I would say at least a few months. Allowing noflat data passing purely on-node is definitely a lot easier than building out and inter-process MPI data passing. But it does require a fair bit of error-checking to make sure that the connections in question are in fact limited to a single process.

**Comment by fzahle** [comment]
Ok, good to know. We can probably get rid of a lot of the non-flattenable connections so we can get up and running under MPI.

**Comment by dykesk** [comment]
closing issue - openmdao currently undergoing refactoring and v. 0.12 is irrelevant
