### ISSUE TITLE
ipython import in fused_helper

### ISSUE THREAD

**Issue by fzahle** [FUSED-Wind/fusedwind#67]
is this import really necessary and could we either remove the code using this or move it to a file that doesn't get imported by every py file in the code?

https://github.com/FUSED-Wind/fusedwind/blob/develop/src/fusedwind/fused_helper.py#L10
https://github.com/FUSED-Wind/fusedwind/blob/develop/src/fusedwind/fused_helper.py#L280-L282

if it should be kept in the codebase, iPython should be listed as a prerequisite for FUSED-Wind.

**Comment by dykesk** [comment]
Yeah – I’ve actually been having our folks comment out some of the fused_helper code due to installation issues; I got it all to work on my machine but seems ipython and pandas can be tricky on windows
