### ISSUE TITLE
Update component base definitions for WISDEM tools

### ISSUE THREAD

**Issue by taylor-parsons** [FUSED-Wind/fusedwind#73]
@implement_base in interface references outdated bases. Examples include HubBase output variables hub_system_mass, hub_system_cm, and hub_system_I whose calculations have been moved to a separate component in DriveSE in order to avoid circular dependency issues at turbine level.

**Comment by dykesk** [comment]
this is a WISDEM issue and was fixed by Taylor in his latest DriveSE updates; closing issue
