### ISSUE TITLE
Add validators to fw-GUI

### ISSUE THREAD

**Issue by gnscott** [FUSED-Wind/fusedwind#79]
Add NumberRange validator to appropriate fields. Change 'Required' validator (deprecated) to DataRequired or InputRequired

**Comment by fzahle** [comment]
do you mean min/max metadata to the parameters in the components, or a validator to the Fields in the GUI code? If the latter this issue belongs in the fusedwind-gui repo.

**Comment by gnscott** [comment]
Sorry – I meant that to be in the fw_gui repo. I’m just figuring out how to add issues with waffle, and it may have ended up in the wrong repo.

George

**Comment by fzahle** [comment]
no problem :-)
